version: "3"
services: 
  web:
    container_name: diastema-web-app
    image: adreaskar/diastema-web-app:latest
    ports:
      - "5400:5400"    
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/docker/
    env_file:
      - ./.env
    command: npm run dev
    restart: always
    depends_on:
      - "mongo"

  # Function Normalization Service
  normalization:
    container_name: function-normalization-service
    image: function-normalization-server-image
    ports: 
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - MONGO_HOST=diastema-mongo
      - MONGO_PORT=27017
      - DATABASE=UIDB
      - COLLECTION=functions
    restart: always

  # Graph Validation Service
  validation:
    container_name: graph-validation-service
    image: graph-validation-image
    ports:
      - "5001:5001"
    environment:
      - HOST=0.0.0.0
      - PORT=5001
      - DIASTEMA_KEY=diastema-key
      - MONGO_HOST=diastema-mongo
      - MONGO_PORT=27017
      - DATABASE=UIDB
      - COLLECTION=datasets
      - DATA_VERIFIER_HOST=host.docker.internal
      - DATA_VERIFIER_PORT=5001
    restart: always

  # Data Verifier Service
  verifier:
    container_name: dummy-data-verifier-service
    image: dummy-data-verifier
    ports:
      - "5002:5002"
    environment:
      - HOST=0.0.0.0
      - PORT=5002
    restart: always

  mongo:
    container_name: diastema-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db: