version: "3"
services: 
  web:
    container_name: diastema-web-app
    image: adreaskar/diastema-web-app:latest
    ports:
      - "5400:5400"    
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/docker/
    env_file:
      - ./.env
    command: npm run dev
    restart: always
    depends_on:
      - "mongo"

  # flask:
  #   container_name: function-normalization-server
  #   image: function-normalization-server-image
  #   ports: 
  #     - "5000:5000"
  #   environment:
  #     - HOST=0.0.0.0
  #     - PORT=5000
  #     - MONGO_HOST=diastema-mongo
  #     - MONGO_PORT=27017
  #     - DATABASE=UIDB
  #     - COLLECTION=functions
  #   restart: always

  mongo:
    container_name: diastema-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db: