version: "3"
services: 
  web:
    container_name: diastema-web-app
    image: adreaskar/diastema-web-app:latest
    ports:
      - "50000:5400"
    env_file:
      - ./.env
    command: node app.js
