version: "3"
services: 
  web:
    container_name: diastema-web-app
    image: web-application-diastema
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "5400:5400"    
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/docker/
    environment:
      - PORT=5400
      - MONGO_URL=mongodb://mongo/
      - ORCHESTRATOR_URL=http://83.212.238.166:50001/analysis
      - ORCHESTRATOR_INGESTION_URL=http://83.212.238.166:50001/ingestion
      - NODE_ENV=development
    command: npm run dev
    restart: always
    depends_on:
      - "mongo"

  mongo:
    container_name: diastema-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
    restart: always

volumes:
  mongo-db: