name: Docker image build and push

on:
  push:
    branches: [ "master" ]

jobs:

  build-push:
    if: github.repository == 'DIASTEMA-UPRC/web-application'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: adreaskar/diastema-web-app:latest
